--------------------------------------------------------
--  DDL for Package HCM_MASTERPAGE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "HCM_MASTERPAGE" IS
 /* Cust-Modify: KOHU-SM2301 */
 -- last update: 02/04/2024 17:14
    PARAM_MSG_ERROR      VARCHAR2(4000 CHAR);
    GLOBAL_V_CODUSER     VARCHAR2(100 CHAR);
    GLOBAL_V_CODPSWD     VARCHAR2(100 CHAR);
    GLOBAL_V_CODEMPID    VARCHAR2(100 CHAR);
    GLOBAL_V_CODCOMP     VARCHAR2(100 CHAR);
    GLOBAL_V_LANG        VARCHAR2(10 CHAR) := '102';
    GLOBAL_V_ZYEAR       NUMBER := 0;
    GLOBAL_V_ZMINLVL     NUMBER;
    GLOBAL_V_ZWRKLVL     NUMBER;
    GLOBAL_V_NUMLVLSALST NUMBER;
    GLOBAL_V_NUMLVLSALEN NUMBER;
    GLOBAL_V_ZUPDSAL     VARCHAR2(100 CHAR);
    P_CODAPP             VARCHAR2(100 CHAR);
    P_MAIN_COLOR         VARCHAR2(100 CHAR);
    P_ADVANCE_COLOR      VARCHAR2(100 CHAR);
    P_FILE_NAME          VARCHAR2(100 CHAR);
    P_MAILLANG           VARCHAR2(100 CHAR);
    V_LIMIT              NUMBER;
    V_START              NUMBER;
    V_CODEMPID           VARCHAR2(4000 CHAR);
    V_STAAPPR            VARCHAR2(100 CHAR);
    V_CODAPP             VARCHAR2(100 CHAR);
    V_CODCOMP            VARCHAR2(100 CHAR);
    TYPE ARR_1D IS
        TABLE OF VARCHAR2(4000 CHAR) INDEX BY BINARY_INTEGER;
    V_ARR_STAAPPR        ARR_1D;

    PROCEDURE GET_FAVORITE(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE SAVE_FAVORITE(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE SAVE_THEME(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE SAVE_LOGO(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE GET_SETTING(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE SAVE_EMAIL_LANGUAGE(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE GET_ALL_ACCOUNT(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );
 -------------------------- Approve Message -----------------------------
    PROCEDURE GET_APPROVE(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    FUNCTION CHKAPPROVEHRES71E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES74E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES77E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES32E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES34E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES36E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES62E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES6AE(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES6IE(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES6KE(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES81E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES88E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES6DE(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES86E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES3BE(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRESS2E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRESS4E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES6ME(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES95E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES84E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES91E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;

    FUNCTION CHKAPPROVEHRES93E(
        P_CODAPP IN VARCHAR2,
        P_CODAPPR IN VARCHAR2
    ) RETURN NUMBER;
 ------------------------------ Request Message -------------------------
    PROCEDURE GET_REQUEST_TOTAL(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    PROCEDURE GET_REQUEST(
        JSON_STR_INPUT IN CLOB,
        JSON_STR_OUTPUT OUT CLOB
    );

    FUNCTION EXPLODE(
        P_DELIMITER VARCHAR2,
        P_STRING LONG,
        P_LIMIT NUMBER
    )RETURN ARR_1D;
END;

/
