--------------------------------------------------------
--  DDL for Package HRES32E
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "HRES32E" is
-- last update: 20/12/2017 18:06
  v_file              utl_file.file_type;
  v_file_name         varchar2 (4000 char);

  l_http_request      utl_http.req;
  l_http_response     utl_http.resp;

  obj_row             json_object_t;
  json_long           long;
  --
  v_chken             varchar2(10 char) := hcm_secur.get_v_chken;
  v_zyear             number;
  p_type              number;
  p_numseq            number;
  p_tabno             number;
  p_numpage           number;
  hres32e_approvno    number;
  --
  v_staappr           varchar2(100 char);
  v_typecod           varchar2(100 char);
  p_limit             varchar2(1000 char);
  p_start             varchar2(1000 char);
  p_end               varchar2(1000 char);
  --
  global_tab2_tab_id  varchar2(100 char);
  global_v_coduser    varchar2(100 char);
  global_v_codpswd    varchar2(100 char);
  global_v_codempid   varchar2(100 char);
  global_v_lang     	varchar2(10 char) := '102';
  global_v_lrunning 	varchar2(10 char);
  global_v_codapp   	varchar2(4000 char);
  b_index_v_dtereq   	date;
  b_index_numseq   	  varchar2(4000 char);
  b_index_typchg   	  varchar2(4000 char);
  ctrl_folder         varchar2(4000 char);
  global_v_flg        varchar2(100 char);
  global_v_zminlvl  	number;
  global_v_zwrklvl  	number;
  global_v_numlvlsalst 	number;
  global_v_numlvlsalen 	number;
  v_zupdsal   			varchar2(4 char);
  --
  b_index_param     	varchar2(4000 char);
  b_index_codempid  	varchar2(4000 char);
  b_index_codcomp   	varchar2(4000 char);
  b_index_dtereq    	date;
  b_index_dtereq_st 	date;
  b_index_dtereq_en 	date;
  b_index_numseqt1  	varchar2(4000 char);
  b_index_numseqt2  	varchar2(4000 char);
  b_index_numseqt3  	varchar2(4000 char);
  b_index_numseqt4  	varchar2(4000 char);
  b_index_numseqt5  	varchar2(4000 char);
  b_index_numseqt6  	varchar2(4000 char);
  v_seqno       	    varchar2(4000 char);
  v_codprov       	  varchar2(4000 char);
  --
  parameter_err     	varchar2(4000 char);
  param_msg_error     varchar2(4000);
  --
  index_codempid      varchar2(4000 char);
  index_desc_codempid varchar2(4000 char);
  index_codempid_query      varchar2(4000 char);
  index_desc_codempid_query varchar2(4000 char);
  index_dtereq        date;
  index_type          varchar2(4000 char);
  index_desc_type     varchar2(4000 char);
  index_numseq        varchar2(4000 char);
  index_status        varchar2(4000 char);
  index_remarkap      varchar2(4000 char);
  index_codappr       varchar2(4000 char);
  index_next_appr     varchar2(4000 char);
  index_staappr       varchar2(4000 char);
  index_codinput      varchar2(4000 char);
  index_dteinput      date;
  index_dtecancel     date;
  index_codapp        varchar2(4000 char);
  --
  tab2_7_numseq     	varchar2(4000 char);
  tab3_numseq         varchar2(4000 char);
  tab6_numseq         varchar2(4000 char);
  --
  tab1_codtitle     	varchar2(4000 char);
  tab1_namfirste    	varchar2(4000 char);
  tab1_namfirstt    	varchar2(4000 char);
  tab1_namfirst3    	varchar2(4000 char);
  tab1_namfirst4    	varchar2(4000 char);
  tab1_namfirst5    	varchar2(4000 char);
  tab1_namlaste     	varchar2(4000 char);
  tab1_namlastt     	varchar2(4000 char);
  tab1_namlast3     	varchar2(4000 char);
  tab1_namlast4     	varchar2(4000 char);
  tab1_namlast5     	varchar2(4000 char);
  tab1_nickname     	temploy1.nickname%type;
  tab1_nicknamt     	temploy1.nicknamt%type;
  tab1_nicknam3     	temploy1.nicknam3%type;
  tab1_nicknam4     	temploy1.nicknam4%type;
  tab1_nicknam5     	temploy1.nicknam5%type;
  tab1_desnote		    varchar2(4000 char);
  tab1_approvno  		  varchar2(4000 char);
  tab1_staappr   		  varchar2(4000 char);
  tab1_codappr   		  varchar2(4000 char);
  tab1_remarkap  		  varchar2(4000 char);
  tab1_dteappr   		  date;
  tab1_routeno   		  varchar2(4000 char);
  tab1_codempap  		  varchar2(4000 char);
  tab1_codcompap 		  varchar2(4000 char);
  tab1_codposap     	varchar2(4000 char);
  tab1_dteinput     	date;
  tab1_dtecancel    	date;
  tab1_p_name       	varchar2(4000 char);
  tab1_p_last       	varchar2(4000 char);
  tab1_p_nick       	varchar2(4000 char);
  tab1_n_name       	varchar2(4000 char);
  tab1_n_last       	varchar2(4000 char);
  tab1_n_nick       	varchar2(4000 char);
  --<< user28 || 12/03/2019 || redmind #6317
  tab1_n_namee       	varchar2(4000 char);
  tab1_n_namet       	varchar2(4000 char);
  tab1_n_name3       	varchar2(4000 char);
  tab1_n_name4       	varchar2(4000 char);
  tab1_n_name5       	varchar2(4000 char);
  tab1_n_laste       	varchar2(4000 char);
  tab1_n_lastt       	varchar2(4000 char);
  tab1_n_last3       	varchar2(4000 char);
  tab1_n_last4       	varchar2(4000 char);
  tab1_n_last5       	varchar2(4000 char);
  tab1_n_nicke       	temploy1.nickname%type;
  tab1_n_nickt       	temploy1.nickname%type;
  tab1_n_nick3       	temploy1.nickname%type;
  tab1_n_nick4       	temploy1.nickname%type;
  tab1_n_nick5       	temploy1.nickname%type;
  -->> user28 || 12/03/2019 || redmind #6317
  tab1_n_codtitle   	varchar2(4000 char);
  tab1_p_codtitle   	varchar2(4000 char);
  --
  tab2_staappr     	  varchar2(4000 char);
  tab2_codbank     	  varchar2(4000 char);
  tab2_dtecancel     	date;
  tab2_dteinput     	date;
  tab2_codposap     	varchar2(4000 char);
  tab2_codappr		    varchar2(400 char);
  tab2_remarkap		    varchar2(400 char);
  tab2_dteappr		    date;
  tab2_routeno		    varchar2(400 char);
  tab2_codempap		    varchar2(400 char);
  tab2_codcompap		  varchar2(400 char);
  tab2_approvno		    varchar2(400 char);
  tab2_numbank2		    varchar2(400 char);
  tab2_numbrnch2	    varchar2(400 char);
  tab2_amtbank		    varchar2(400 char);
  tab2_numbank		    varchar2(400 char);
  tab2_numbrnch		    varchar2(400 char);
  tab2_numlicid		    varchar2(400 char);
  tab2_dtelicid		    date;
  tab2_desc_codbank   varchar2(4000 char);
--  tab2_codfnatn		    varchar2(4000 char);
--  tab2_codfrelg		    varchar2(4000 char);
--  tab2_codfoccu		    varchar2(4000 char);
--  tab2_numofidf		    varchar2(4000 char);
--  tab2_codmnatn		    varchar2(4000 char);
--  tab2_codmrelg		    varchar2(4000 char);
--  tab2_codmoccu		    varchar2(4000 char);
--  tab2_numofidm		    varchar2(4000 char);
  tab2_codsubdistr  	varchar2(4000 char);
  tab2_codsubdistc  	varchar2(4000 char);
  tab2_coddistc  		varchar2(4000 char);
  tab2_codprovc  		varchar2(4000 char);
  tab2_codcntyc  		varchar2(4000 char);
  tab2_codpostc 		varchar2(4000 char);
  tab2_numtelec 		varchar2(4000 char);
--  tab2_adrcont1 		varchar2(4000 char);
--  tab2_codpost 		    varchar2(4000 char);
--  tab2_numtele 		    varchar2(4000 char);
--  tab2_email 			varchar2(4000 char);
--  tab2_numfax 		    varchar2(4000 char);
--  tab2_desrelat 		varchar2(4000 char);
  tab2_namcont 		    varchar2(4000 char);
  tab2_adrissue 		varchar2(4000 char);
  tab2_codprovi 		varchar2(4000 char);
  tab2_dteoffid 		date;
  tab2_numpasid 		varchar2(4000 char);
  tab2_dtepasid 		date;
  tab2_dteprmen 		date;
  tab2_numspid		    varchar2(4000 char);
  tab2_stamilit       varchar2(4000 char);
  tab2_adrrege        varchar2(4000 char);
  tab2_adrregt        varchar2(4000 char);
  tab2_adrreg3        varchar2(4000 char);
  tab2_adrreg4        varchar2(4000 char);
  tab2_adrreg5        varchar2(4000 char);
  tab2_coddistr       varchar2(4000 char);
  tab2_codprovr       varchar2(4000 char);
  tab2_codcntyr       varchar2(4000 char);
  tab2_codpostr       varchar2(4000 char);
  tab2_adrconte       varchar2(4000 char);
  tab2_adrcontt       varchar2(4000 char);
  tab2_adrcont3       varchar2(4000 char);
  tab2_adrcont4       varchar2(4000 char);
  tab2_adrcont5       varchar2(4000 char);
  tab2_numprmid       varchar2(4000 char);
  tab2_dteprmst       date;
  tab2_stamarry       varchar2(4000 char);
  tab2_email_emp      varchar2(4000 char);
  tab2_nummobile      temploy1.nummobile%type;
  tab2_lineid         temploy1.lineid%type;
  tab2_numvisa        temploy2.numvisa%type;
  tab2_dtevisaexp     temploy2.dtevisaexp%type;
  tab2_codclnsc       temploy2.codclnsc%type;
  tab2_dteretire      temploy1.dteretire%type;
  tab2_adrreg         varchar2(4000 char);
  tab2_adrcont        varchar2(4000 char);
  tab2_codbank2       varchar2(4000 char);
  tab2_qtychedu       varchar2(4000 char);
  tab2_qtychned       varchar2(4000 char);
  tab2_amttranb       temploy3.amttranb%type;
  tab2_dessubdistr    varchar2(4000 char);
  tab2_desdistr       varchar2(4000 char);
  tab2_desprovr       varchar2(4000 char);
  tab2_descntyr       varchar2(4000 char);
  tab2_dessubdistc    varchar2(4000 char);
  tab2_desdistc       varchar2(4000 char);
  tab2_desprovc       varchar2(4000 char);
  tab2_descntyc       varchar2(4000 char);
  tab2_desprovi       varchar2(4000 char);
--  tab2_namspous       varchar2(4000 char);
  tab2_desnote6       varchar2(4000 char);
  tab2_desc_codbank2  varchar2(4000 char);
  tab2_desc_codspocc  varchar2(4000 char);
  tab2_desc_codsppro  varchar2(4000 char);
  tab2_desc_codspcty  varchar2(4000 char);
-----*Spouse*
  tab2_codempidsp         tspouse.codempidsp%type;
  tab2_namimgsp           tspouse.namimgsp%type;
  tab2_codtitle           tspouse.codtitle%type;
  tab2_namfirst           tspouse.namfirste%type;
  tab2_namfirste          tspouse.namfirste%type;
  tab2_namfirstt          tspouse.namfirstt%type;
  tab2_namfirst3          tspouse.namfirst3%type;
  tab2_namfirst4          tspouse.namfirst4%type;
  tab2_namfirst5          tspouse.namfirst5%type;
  tab2_namlast            tspouse.namlaste%type;
  tab2_namlaste           tspouse.namlaste%type;
  tab2_namlastt           tspouse.namlastt%type;
  tab2_namlast3           tspouse.namlast3%type;
  tab2_namlast4           tspouse.namlast4%type;
  tab2_namlast5           tspouse.namlast5%type;
  tab2_namspe             tspouse.namspe%type;
  tab2_namspt             tspouse.namspt%type;
  tab2_namsp3             tspouse.namsp3%type;
  tab2_namsp4             tspouse.namsp4%type;
  tab2_namsp5             tspouse.namsp5%type;
  tab2_numoffid           tspouse.numoffid%type;
  tab2_numtaxid           tspouse.numtaxid%type;
  tab2_codspocc           tspouse.codspocc%type;
  tab2_dtespbd            tspouse.dtespbd%type;
  tab2_stalife            tspouse.stalife%type;
  tab2_staincom           tspouse.staincom%type;
  tab2_dtedthsp           tspouse.dtedthsp%type;
  tab2_desnoffi           tspouse.desnoffi%type;
  tab2_numfasp            tspouse.numfasp%type;
  tab2_nummosp            tspouse.nummosp%type;
  tab2_dtemarry           tspouse.dtemarry%type;
  tab2_codsppro           tspouse.codsppro%type;
  tab2_codspcty           tspouse.codspcty%type;
  tab2_desplreg           tspouse.desplreg%type;
  tab2_desnote            tspouse.desnote%type;
  tab2_filename           tspouse.filename%type;
  tab2_numrefdoc          tspouse.numrefdoc%type;
--------*End Spouse*
--------*Travel*
  tab2_typtrav            temploy1.typtrav%type;
  tab2_qtylength          temploy1.qtylength%type;
  tab2_carlicen           temploy1.carlicen%type;
  tab2_typfuel            temploy1.typfuel%type;
  tab2_codbusno           temploy1.codbusno%type;
  tab2_codbusrt           temploy1.codbusrt%type;
--------*End Travel*
--------*Family*
  tab2_codempfa         tfamily.codempfa%type;
  tab2_codtitlf         tfamily.codtitlf%type;
  tab2_namfstfe         tfamily.namfstfe%type;
  tab2_namfstft         tfamily.namfstft%type;
  tab2_namfstf3         tfamily.namfstf3%type;
  tab2_namfstf4         tfamily.namfstf4%type;
  tab2_namfstf5         tfamily.namfstf5%type;
  tab2_namlstfe         tfamily.namlstfe%type;
  tab2_namlstft         tfamily.namlstft%type;
  tab2_namlstf3         tfamily.namlstf3%type;
  tab2_namlstf4         tfamily.namlstf4%type;
  tab2_namlstf5         tfamily.namlstf5%type;
  tab2_namfathe         tfamily.namfathe%type;
  tab2_namfatht         tfamily.namfatht%type;
  tab2_namfath3         tfamily.namfath3%type;
  tab2_namfath4         tfamily.namfath4%type;
  tab2_namfath5         tfamily.namfath5%type;
  tab2_numofidf         tfamily.numofidf%type;
  tab2_dtebdfa          tfamily.dtebdfa%type;
  tab2_codfnatn         tfamily.codfnatn%type;
  tab2_codfrelg         tfamily.codfrelg%type;
  tab2_codfoccu         tfamily.codfoccu%type;
  tab2_staliff          tfamily.staliff%type;
  tab2_dtedeathf        tfamily.dtedeathf%type;
  tab2_filenamf         tfamily.filenamf%type;
  tab2_numrefdocf       tfamily.numrefdocf%type;
  tab2_codempmo         tfamily.codempmo%type;
  tab2_codtitlm         tfamily.codtitlm%type;
  tab2_namfstme         tfamily.namfstme%type;
  tab2_namfstmt         tfamily.namfstmt%type;
  tab2_namfstm3         tfamily.namfstm3%type;
  tab2_namfstm4         tfamily.namfstm4%type;
  tab2_namfstm5         tfamily.namfstm5%type;
  tab2_namlstme         tfamily.namlstme%type;
  tab2_namlstmt         tfamily.namlstmt%type;
  tab2_namlstm3         tfamily.namlstm3%type;
  tab2_namlstm4         tfamily.namlstm4%type;
  tab2_namlstm5         tfamily.namlstm5%type;
  tab2_nammothe         tfamily.nammothe%type;
  tab2_nammotht         tfamily.nammotht%type;
  tab2_nammoth3         tfamily.nammoth3%type;
  tab2_nammoth4         tfamily.nammoth4%type;
  tab2_nammoth5         tfamily.nammoth5%type;
  tab2_numofidm         tfamily.numofidm%type;
  tab2_dtebdmo          tfamily.dtebdmo%type;
  tab2_codmnatn         tfamily.codmnatn%type;
  tab2_codmrelg         tfamily.codmrelg%type;
  tab2_codmoccu         tfamily.codmoccu%type;
  tab2_stalifm          tfamily.stalifm%type;
  tab2_dtedeathm        tfamily.dtedeathm%type;
  tab2_filenamm         tfamily.filenamm%type;
  tab2_numrefdocm       tfamily.numrefdocm%type;
  tab2_codtitlc         tfamily.codtitlc%type;
  tab2_namfstce         tfamily.namfstce%type;
  tab2_namfstct         tfamily.namfstct%type;
  tab2_namfstc3         tfamily.namfstc3%type;
  tab2_namfstc4         tfamily.namfstc4%type;
  tab2_namfstc5         tfamily.namfstc5%type;
  tab2_namlstce         tfamily.namlstce%type;
  tab2_namlstct         tfamily.namlstct%type;
  tab2_namlstc3         tfamily.namlstc3%type;
  tab2_namlstc4         tfamily.namlstc4%type;
  tab2_namlstc5         tfamily.namlstc5%type;
  tab2_namconte         tfamily.namconte%type;
  tab2_namcontt         tfamily.namcontt%type;
  tab2_namcont3         tfamily.namcont3%type;
  tab2_namcont4         tfamily.namcont4%type;
  tab2_namcont5         tfamily.namcont5%type;
  tab2_adrcont1         tfamily.adrcont1%type;
  tab2_codpost          tfamily.codpost%type;
  tab2_numtele          tfamily.numtele%type;
  tab2_numfax           tfamily.numfax%type;
  tab2_email            tfamily.email%type;
  tab2_desrelat         tfamily.desrelat%type;
--------*End Family*
  tab261_coddeduct    varchar2(4000 char);
  tab261_amtdeduct    varchar2(4000 char);
  tab261_amtdeduct_spous varchar2(4000 char);
  tab262_coddeduct    varchar2(4000 char);
  tab262_amtdeduct    varchar2(4000 char);
  tab262_amtdeduct_spous varchar2(4000 char);
  tab263_coddeduct    varchar2(4000 char);
  tab263_amtdeduct    varchar2(4000 char);
  tab263_amtdeduct_spous varchar2(4000 char);
  tab26_box_items     json_object_t;
  tab26_box_items1    json_object_t;
  tab26_box_items2    json_object_t;
  tab26_box_items3    json_object_t;

  p_typdeduct         varchar2(4000 char);
  v_amtdeduct 	      varchar2(20);
  box_item_no         number;
  box_item_no26       number;
  v_box_item_no       varchar2(100 char);
  v_box_json          json_object_t;
  v_box_json26        json_object_t;
  v_v                 varchar2(4000 char);
  box_item_no261      number;
  v_box_json261       json_object_t;
  v_box_json262       json_object_t;
  v_box_json263       json_object_t;
  --
  tab3_codedlv    	  varchar2(4000 char);
  tab3_desc_codedlv	  varchar2(4000 char);
  tab3_coddglv    	  varchar2(4000 char);
  tab3_desc_coddglv 	varchar2(4000 char);
  tab3_codmajsb   	  varchar2(4000 char);
  tab3_desc_codmajsb	varchar2(4000 char);
  tab3_codminsb   	  varchar2(4000 char);
  tab3_codinst		    varchar2(4000 char);
  tab3_dteinput		    varchar2(4000 char);
  tab3_dtecancel		  varchar2(4000 char);
  tab3_desc_codinst  	varchar2(4000 char);
  tab3_codcount   	  varchar2(4000 char);
  tab3_desc_codcount 	varchar2(4000 char);
  tab3_numgpa     	  varchar2(4000 char);
  tab3_dtegyear   	  varchar2(4000 char);
  tab3_stayear    	  varchar2(4000 char);
  tab3_flgeduc		    varchar2(4000 char);
  tab3_routeno  		  varchar2(4000 char);
  tab3_codempap 		  varchar2(4000 char);
  tab3_codcompap		  varchar2(4000 char);
  tab3_codposap 		  varchar2(4000 char);
  tab3_staappr   		  varchar2(4000 char);
  tab3_approvno  		  varchar2(4000 char);
  tab3_codappr   		  varchar2(4000 char);
  tab3_dteappr   		  varchar2(4000 char);
  tab3_remarkap  		  varchar2(4000 char);
  --
  --*Work Exp*
  tab_work_exp_numseq             tapplwex.numseq%type;
  tab_work_exp_desnoffi           tapplwex.desnoffi%type;
  tab_work_exp_deslstjob1         tapplwex.deslstjob1%type;
  tab_work_exp_deslstpos          tapplwex.deslstpos%type;
  tab_work_exp_desoffi1           tapplwex.desoffi1%type;
  tab_work_exp_numteleo           tapplwex.numteleo%type;
  tab_work_exp_namboss            tapplwex.namboss%type;
  tab_work_exp_desres             tapplwex.desres%type;
  tab_work_exp_amtincom           tapplwex.amtincom%type;
  tab_work_exp_dtestart           tapplwex.dtestart%type;
  tab_work_exp_dteend             tapplwex.dteend%type;
  tab_work_exp_remark             tapplwex.remark%type;
  tab_work_exp_dteupd             tapplwex.dteupd%type;
  tab_work_exp_coduser            tapplwex.coduser%type;
  tab_work_exp_desjob             tapplwex.desjob%type;
  tab_work_exp_desrisk            tapplwex.desrisk%type;
  tab_work_exp_desprotc           tapplwex.desprotc%type;
  --
--------*Childrn*
  tab4_numseq             tchildrn.numseq%type;
  tab4_codtitle           tchildrn.codtitle%type;
  tab4_namfirste          tchildrn.namfirste%type;
  tab4_namfirstt          tchildrn.namfirstt%type;
  tab4_namfirst3          tchildrn.namfirst3%type;
  tab4_namfirst4          tchildrn.namfirst4%type;
  tab4_namfirst5          tchildrn.namfirst5%type;
  tab4_namlaste           tchildrn.namlaste%type;
  tab4_namlastt           tchildrn.namlastt%type;
  tab4_namlast3           tchildrn.namlast3%type;
  tab4_namlast4           tchildrn.namlast4%type;
  tab4_namlast5           tchildrn.namlast5%type;
  tab4_namche             tchildrn.namche%type;
  tab4_namcht             tchildrn.namcht%type;
  tab4_namch3             tchildrn.namch3%type;
  tab4_namch4             tchildrn.namch4%type;
  tab4_namch5             tchildrn.namch5%type;
  tab4_numoffid           tchildrn.numoffid%type;
  tab4_dtechbd            tchildrn.dtechbd%type;
  tab4_codsex             tchildrn.codsex%type;
  tab4_codedlv            tchildrn.codedlv%type;
  tab4_stachld            tchildrn.stachld%type;
  tab4_stalife            tchildrn.stalife%type;
  tab4_dtedthch           tchildrn.dtedthch%type;
  tab4_flginc             tchildrn.flginc%type;
  tab4_flgedlv            tchildrn.flgedlv%type;
  tab4_flgdeduct          tchildrn.flgdeduct%type;
  tab4_stabf              tchildrn.stabf%type;
  tab4_filename           tchildrn.filename%type;
  tab4_numrefdoc          tchildrn.numrefdoc%type;
--------*End Childrn*
  tab4_dteinput		    varchar2(4000 char);
  tab4_dtecancel		  varchar2(4000 char);
  tab4_routeno  		  varchar2(4000 char);
  tab4_codempap 		  varchar2(4000 char);
  tab4_codcompap		  varchar2(4000 char);
  tab4_codposap 		  varchar2(4000 char);
  tab4_staappr     	  varchar2(4000 char);
  tab4_approvno    	  varchar2(4000 char);
  tab4_codappr     	  varchar2(4000 char);
  tab4_dteappr     	  varchar2(4000 char);
  tab4_remarkap    	  varchar2(4000 char);
  tab4_box_items      json_object_t;
  tab4_status 	 	    varchar2(4000 char);
  --
  tab5_typrewd      	varchar2(4000 char);
  tab5_desc_typrewd 	varchar2(4000 char);
  tab5_dteinput	 	    varchar2(4000 char);
  tab5_dtecancel	 	  varchar2(4000 char);
  tab5_desrewd1    	  varchar2(4000 char);
  tab5_numhmref     	varchar2(4000 char);
  tab5_routeno  		  varchar2(4000 char);
  tab5_codempap 		  varchar2(4000 char);
  tab5_codcomp 		    varchar2(4000 char);
  tab5_codpos 		    varchar2(4000 char);
  tab5_codjob 		    varchar2(4000 char);
  tab5_numlvl 		    varchar2(4000 char);
  tab5_codcompap		  varchar2(4000 char);
  tab5_codposap 		  varchar2(4000 char);
  tab5_staappr     	  varchar2(4000 char);
  tab5_approvno    	  varchar2(4000 char);
  tab5_codappr     	  varchar2(4000 char);
  tab5_dteappr     	  varchar2(4000 char);
  tab5_remarkap    	  varchar2(4000 char);
  --
  tab6_routeno  		  varchar2(4000 char);
  tab6_codempap 		  varchar2(4000 char);
  tab6_codcompap		  varchar2(4000 char);
  tab6_codposap 		  varchar2(4000 char);
  tab6_staappr     	  varchar2(4000 char);
  tab6_approvno    	  varchar2(4000 char);
  tab6_codappr     	  varchar2(4000 char);
  tab6_dteappr     	  varchar2(4000 char);
  tab6_dtecancel     	varchar2(4000 char);
  tab6_remarkap    	  varchar2(4000 char);
  tab6_dteinput		    varchar2(4000 char);
  tab6_destrain	 	    varchar2(4000 char);
  tab6_dtetrain	 	    date;
  tab6_dtetren	 	    date;
  tab6_dtetr	 		    varchar2(4000 char);
  tab6_desplace	 	    varchar2(4000 char);
  tab6_desinstu	 	    varchar2(4000 char);
  tab6_filedoc	 	    varchar2(4000 char);
  tab6_status 	 	    varchar2(4000 char);
  tab6_desc_status    varchar2(4000 char);
  tab6_box_items      json_object_t;
  --
  tab21_amtdeduct     varchar2(4000 char);
  --
  tab27_numseq		    varchar2(400 char);
  tab27_typdoc		    varchar2(400 char);
  tab27_dteinput		  varchar2(400 char);
  tab27_dtecancel		  varchar2(400 char);
  tab27_namdoc		    varchar2(4000 char);
  tab27_dterecv		    date;
  tab27_dtedocen		  date;
  tab27_numdoc		    varchar2(4000 char);
  tab27_filedoc		    varchar2(4000 char);
  tab27_desnote		    varchar2(4000 char);
  tab27_flgresume		  tappldoc.flgresume%type;
  tab27_box_items     json_object_t;
  tab27_status 	 	    varchar2(4000 char);
  --
-----*Relative*
  tab2_relatives_numseq            trelatives.numseq%type;
  tab2_relatives_codemprl          trelatives.codemprl%type;
  tab2_relatives_namrele           trelatives.namrele%type;
  tab2_relatives_namrelt           trelatives.namrelt%type;
  tab2_relatives_namrel3           trelatives.namrel3%type;
  tab2_relatives_namrel4           trelatives.namrel4%type;
  tab2_relatives_namrel5           trelatives.namrel5%type;
  tab2_relatives_numtelec          trelatives.numtelec%type;
  tab2_relatives_adrcomt           trelatives.adrcomt%type;
-----*End Relative*
--*Competency*
  tab_competency_codtency         tcmptncy.codtency%type;
  tab_competency_grade            tcmptncy.grade%type;
--*End Competency
--*Lang Abi*
  tab_lang_abi_codlang        tlangabi.codlang%type;
  tab_lang_abi_flglist        tlangabi.flglist%type;
  tab_lang_abi_flgspeak       tlangabi.flgspeak%type;
  tab_lang_abi_flgread        tlangabi.flgread%type;
  tab_lang_abi_flgwrite       tlangabi.flgwrite%type;
--*End Lang Abi*
--*His Reward*
  tab_his_reward_dteinput         thisrewd.dteinput%type;
  tab_his_reward_typrewd          thisrewd.typrewd%type;
  tab_his_reward_desrewd1         thisrewd.desrewd1%type;
  tab_his_reward_numhmref         thisrewd.numhmref%type;
  tab_his_reward_filename         thisrewd.filename%type;
--*End His Reward*

  tab31_flgupdat     	varchar2(4000 char);
  tab31_codcnty    	  varchar2(4000 char);
  tab31_codedlv		    varchar2(4000 char);
  tab31_numseq		    varchar2(4000 char);
  tab31_coddglv	  	  varchar2(4000 char);
  tab31_codmajsb		  varchar2(4000 char);
  tab31_codminsb		  varchar2(4000 char);
  tab31_codinst		    varchar2(4000 char);
  tab31_codcount		  varchar2(4000 char);
  tab31_routeno   	  varchar2(4000 char);
  tab31_codempap  	  varchar2(4000 char);
  tab31_codcompap 	  varchar2(4000 char);
  tab31_codposap  	  varchar2(4000 char);
  tab31_staappr   	  varchar2(4000 char);
  tab31_approvno  	  varchar2(4000 char);
  tab31_codappr   	  varchar2(4000 char);
  tab31_dteappr   	  varchar2(4000 char);
  tab31_remarkap  	  varchar2(4000 char);
  tab31_flgeduc		    varchar2(4000 char);
  tab31_numgpa		    varchar2(4000 char);
  tab31_dtegyear		  varchar2(4000 char);
  tab31_flgupd		    varchar2(4000 char);
  tab31_stayear		    varchar2(4000 char);
  tab31_desc_codedlv  varchar2(4000 char);
  tab31_desc_coddglv  varchar2(4000 char);
  tab31_desc_codmajsb varchar2(4000 char);
  tab31_desc_codminsb varchar2(4000 char);
  tab31_desc_codinst  varchar2(4000 char);
  tab31_desc_codcount varchar2(4000 char);
  tab31_box_items     json_object_t;
  tab31_status 	 	    varchar2(4000 char);
  --
  tab61_numseq     	  varchar2(4000 char);
  tab61_flgupd     	  varchar2(4000 char);
  tab61_desinstu	 	  varchar2(4000 char);
  tab61_desplace     	varchar2(4000 char);
  tab61_routeno   	  varchar2(4000 char);
  tab61_codempap  	  varchar2(4000 char);
  tab61_codcompap 	  varchar2(4000 char);
  tab61_codposap  	  varchar2(4000 char);
  tab61_staappr     	varchar2(4000 char);
  tab61_approvno    	varchar2(4000 char);
  tab61_codappr     	varchar2(4000 char);
  tab61_dteappr     	varchar2(4000 char);
  tab61_remarkap    	varchar2(4000 char);
  tab61_destrain      varchar2(4000 char);
  tab61_filedoc       varchar2(4000 char);
  tab61_dtetrain      date;
  tab61_dtetren       date;
  --
  tab222_qtychedu		  varchar2(400 char);
  tab222_qtychned		  varchar2(4000 char);
  --
  others_data_routeno   varchar2(4000 char);
  others_data_staappr   varchar2(4000 char);
  others_data_approvno  varchar2(4000 char);
  others_data_codappr   varchar2(4000 char);
  others_data_dteappr   varchar2(4000 char);
  others_data_remarkap  varchar2(4000 char);
  others_data_codempap  varchar2(4000 char);
  others_data_codcompap	varchar2(4000 char);
  others_data_codposap 	varchar2(4000 char);
  type arr_key is table of varchar2(600 char) index by varchar2(600 char);
  tab_fldedit   arr_key;
  --
  procedure initial_value(json_str in clob);
  procedure initial_value_tab2_7(json_str in clob);
  procedure initial_value_tab2_6(json_str in clob, p_flg in varchar2);
  procedure initial_value_tab3(json_str in clob);
  procedure initial_value_tab4(json_str in clob);
  procedure initial_value_tab6(json_str in clob);
  procedure hres32e_check_index;
  procedure check_index;
  function get_resp_json_str return clob;
  function get_numseq return varchar2;
  function get_staappr(json_str in clob) return varchar2;
  procedure insert_next_step(p_type in varchar2,p_numseq in number);

  --save_data
  procedure ess_save_tab1(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_1(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_2(json_str in clob, resp_json_str out clob);
  procedure ess_save_travel(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_3(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_4(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_5(json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_6(param_json_clob in clob,global_json_str in clob, resp_json_str out clob);
  procedure ess_save_tab2_7(param_json_clob in clob, resp_json_str out clob);
--  procedure ess_save_tab4(param_json_clob in clob,global_json_str in clob, resp_json_str out varchar2);
  procedure ess_save_tab4(json_str_input in clob, json_str_output out clob);
  procedure ess_save_tab5(json_str in clob, resp_json_str out clob);
--  procedure ess_save_tab6(param_json_clob in clob,global_json_str in clob, resp_json_str out varchar2);
  procedure ess_save_tab6(json_str_input in clob, json_str_output out clob);
  procedure ess_save_relatives(json_str_input in clob, json_str_output out clob);
  procedure ess_save_education(json_str_input in clob, json_str_output out clob);
  procedure ess_save_work_exp(json_str_input in clob, json_str_output out clob);
  procedure ess_save_competency(json_str_input in clob, json_str_output out clob);
  procedure ess_save_lang_abi(json_str_input in clob, json_str_output out clob);
  procedure ess_save_his_reward(json_str_input in clob, json_str_output out clob);
  procedure ess_save_others_data(json_str_input in clob, json_str_output out clob);

  --get_data
  function hres32e_index(json_str in clob) return clob;
  function hres32e_detail_tab1(json_str in clob) return clob;
  function hres32e_detail_tab2(json_str in clob) return clob;
  function hres32e_detail_tab3(json_str in clob) return clob;
  function hres32e_detail_tab4(json_str in clob) return clob;
  function hres32e_detail_tab5(json_str in clob) return clob;
  function hres32e_detail_tab6(json_str in clob) return clob;
  function hres32e_detail_tab7(json_str in clob) return clob;
  function hres32e_detail_tab8_1(json_str in clob) return clob;
  function hres32e_detail_tab8_2(json_str in clob) return clob;
  function hres32e_detail_tab8_3(json_str in clob) return clob;
  function hres32e_detail_tab9(json_str in clob) return clob;
  function hres32e_detail_tab10(json_str in clob) return clob;
  function hres32e_tab2_relatives(json_str in clob) return clob;
  function hres32e_tab3_work_exp(json_str in clob) return clob;
  function hres32e_tab5_competency(json_str in clob) return clob;
  function hres32e_tab5_lang_abi(json_str in clob) return clob;
  function hres32e_tab5_his_reward(json_str in clob) return clob;
  --
  function gen_index_data return clob;
  function get_tnamech return clob;
  function get_address return clob;
  function get_tfamily return clob;
  function get_document return clob;
  function get_trewdreq return clob;
  function get_education return clob;
  function get_childen return clob;
  function get_tdeductd_e return clob;
  function get_tdeductd_d return clob;
  function get_tdeductd_o return clob;
  function get_tempch return varchar2;
  function get_ttrainbf return clob;
  function get_relatives return clob;
  function get_work_exp return clob;
  function get_competency return clob;
  function get_lang_abi return clob;
  function get_his_reward return clob;

  function gen_numseq_tab27 return number;
  function gen_numseq_tab3 return number;
  function gen_numseq_tab4 return number;
  function gen_numseq_tab6 return number;

  --cancel,delete,edit
  procedure ess_cancel_hres32e(json_str in clob, resp_json_str out clob);
  procedure ess_del_tab2_7(v_seqno in varchar2);
  procedure ess_del_tab3(json_str in clob, resp_json_str out clob);
  procedure ess_del_tab4(json_str in clob, resp_json_str out clob);
  procedure ess_del_tab6(json_str in clob, resp_json_str out clob);
  procedure ess_del_temeslog2(p_numpage varchar2,p_key in varchar2,p_field_key in varchar2,p_type_key varchar2 default 'N');
  --
  function get_others_data(json_str in clob) return clob;
end; -- Package spec

/
