--------------------------------------------------------
--  DDL for Package HRMS33U
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "HRMS33U" is
-- last update: 27/09/2022 10:44

  param_msg_error           varchar2(4000 char);
  param_msg_error_mail      varchar2(4000 char);
  global_v_coduser          varchar2(100 char);
  global_v_codempid         varchar2(100 char);
  global_v_codpswd          varchar2(100 char);
  global_v_lang             varchar2(10 char);
  global_v_zyear            number := 0;
  global_v_zminlvl          number;
  global_v_zwrklvl          number;
  global_v_numlvlsalst      number;
  global_v_numlvlsalen      number;
  global_v_zupdsal          varchar2(100 char);
  b_index_v_dtereq   	date;
  b_index_numseq   	  varchar2(4000 char);
  b_index_typchg   	  varchar2(4000 char);
  ctrl_folder         varchar2(4000 char);
  param_sqlerrm       varchar2(4000 char);
  p_lang            varchar2(10) := '102';
  v_chken             varchar2(10 char) := hcm_secur.get_v_chken;
  v_zyear             number;

  p_codempid                varchar2(1000 char);
  p_codcomp                 varchar2(1000 char);
  p_codcompy                 varchar2(10 char);
  p_dtest       varchar2(100 char);
  p_dteen       varchar2(100 char);
  p_staappr     varchar2(100 char);
  p_start       number;
  p_end         number;
  v_codappr       varchar2(50 char) ;

  b_index_param     	varchar2(4000 char);
  b_index_codempid  	varchar2(4000 char);
  b_index_codcomp   	varchar2(4000 char);
  b_index_dtereq    	date;
  b_index_dtereq_st 	date;
  b_index_dtereq_en 	date;
  b_index_numseqt1  	varchar2(4000 char);
  b_index_numseqt2  	varchar2(4000 char);
  b_index_numseqt3  	varchar2(4000 char);
  b_index_numseqt4  	varchar2(4000 char);
  b_index_numseqt5  	varchar2(4000 char);
  b_index_numseqt6  	varchar2(4000 char);
  v_seqno       	    varchar2(4000 char);

  tab6_numseq         varchar2(4000 char);

  --
  tab1_codtitle     	varchar2(4000 char);
  tab1_namfirste    	varchar2(4000 char);
  tab1_namfirstt    	varchar2(4000 char);
  tab1_namfirst3    	varchar2(4000 char);
  tab1_namfirst4    	varchar2(4000 char);
  tab1_namfirst5    	varchar2(4000 char);
  tab1_namlaste     	varchar2(4000 char);
  tab1_namlastt     	varchar2(4000 char);
  tab1_namlast3     	varchar2(4000 char);
  tab1_namlast4     	varchar2(4000 char);
  tab1_namlast5     	varchar2(4000 char);
  tab1_nickname     	temploy1.nickname%type;
  tab1_nicknamt     	temploy1.nicknamt%type;
  tab1_nicknam3     	temploy1.nicknam3%type;
  tab1_nicknam4     	temploy1.nicknam4%type;
  tab1_nicknam5     	temploy1.nicknam5%type;
  tab1_desnote		    varchar2(4000 char);
  tab1_approvno  		  varchar2(4000 char);
  tab1_staappr   		  varchar2(4000 char);
  tab1_codappr   		  varchar2(4000 char);
  tab1_remarkap  		  varchar2(4000 char);
  tab1_dteappr   		  date;
  tab1_routeno   		  varchar2(4000 char);
  tab1_codempap  		  varchar2(4000 char);
  tab1_codcompap 		  varchar2(4000 char);
  tab1_codposap     	varchar2(4000 char);
  tab1_dteinput     	date;
  tab1_dtecancel    	date;
  tab1_p_name       	varchar2(4000 char);
  tab1_p_last       	varchar2(4000 char);
  tab1_p_nick       	varchar2(4000 char);
  tab1_n_name       	varchar2(4000 char);
  tab1_n_last       	varchar2(4000 char);
  tab1_n_nick       	varchar2(4000 char);
  --<< user28 || 12/03/2019 || redmind #6317
  tab1_n_namee       	varchar2(4000 char);
  tab1_n_namet       	varchar2(4000 char);
  tab1_n_name3       	varchar2(4000 char);
  tab1_n_name4       	varchar2(4000 char);
  tab1_n_name5       	varchar2(4000 char);
  tab1_n_laste       	varchar2(4000 char);
  tab1_n_lastt       	varchar2(4000 char);
  tab1_n_last3       	varchar2(4000 char);
  tab1_n_last4       	varchar2(4000 char);
  tab1_n_last5       	varchar2(4000 char);
  tab1_n_nicke       	temploy1.nickname%type;
  tab1_n_nickt       	temploy1.nickname%type;
  tab1_n_nick3       	temploy1.nickname%type;
  tab1_n_nick4       	temploy1.nickname%type;
  tab1_n_nick5       	temploy1.nickname%type;
  -->> user28 || 12/03/2019 || redmind #6317
  tab1_n_codtitle   	varchar2(4000 char);
  tab1_p_codtitle   	varchar2(4000 char);
   --
  tab2_staappr     	  varchar2(4000 char);
  tab2_codbank     	  varchar2(4000 char);
  tab2_dtecancel     	date;
  tab2_dteinput     	date;
  tab2_codposap     	varchar2(4000 char);
  tab2_codappr		    varchar2(400 char);
  tab2_remarkap		    varchar2(400 char);
  tab2_dteappr		    date;
  tab2_routeno		    varchar2(400 char);
  tab2_codempap		    varchar2(400 char);
  tab2_codcompap		  varchar2(400 char);
  tab2_approvno		    varchar2(400 char);
  tab2_numbank2		    varchar2(400 char);
  tab2_numbrnch2	    varchar2(400 char);
  tab2_amtbank		    varchar2(400 char);
  tab2_numbank		    varchar2(400 char);
  tab2_numbrnch		    varchar2(400 char);
  tab2_numlicid		    temploy2.numlicid%type;
  tab2_dtelicid		    temploy2.dtelicid%type;
  tab2_desc_codbank   varchar2(4000 char);
--  tab2_codfnatn		    varchar2(4000 char);
--  tab2_codfrelg		    varchar2(4000 char);
--  tab2_codfoccu		    varchar2(4000 char);
--  tab2_numofidf		    varchar2(4000 char);
--  tab2_codmnatn		    varchar2(4000 char);
--  tab2_codmrelg		    varchar2(4000 char);
--  tab2_codmoccu		    varchar2(4000 char);
--  tab2_numofidm		    varchar2(4000 char);
  tab2_codsubdistr  	temploy2.codsubdistr%type;
  tab2_codsubdistc  	temploy2.codsubdistc%type;
  tab2_coddistc  		  temploy2.coddistc%type;
  tab2_codprovc  		  temploy2.codprovc%type;
  tab2_codcntyc  		  temploy2.codcntyc%type;
  tab2_codpostc 		  temploy2.codpostc%type;
  tab2_numtelec 		  temploy2.numtelec%type;
--  tab2_adrcont1 		varchar2(4000 char);
--  tab2_codpost 		    varchar2(4000 char);
--  tab2_numtele 		    varchar2(4000 char);
--  tab2_email 			varchar2(4000 char);
--  tab2_numfax 		    varchar2(4000 char);
--  tab2_desrelat 		varchar2(4000 char);
  tab2_namcont 		    varchar2(4000 char);
  tab2_adrissue 		  temploy2.adrissue%type;
  tab2_codprovi 		  temploy2.codprovi%type;
  tab2_dteoffid 		  temploy2.dteoffid%type;
  tab2_numpasid 		  temploy2.numpasid%type;
  tab2_dtepasid 		  temploy2.dtepasid%type;
  tab2_dteprmen 		  temploy2.dteprmen%type;
  tab2_numspid		    varchar2(4000 char);
  tab2_stamilit       temploy1.stamilit%type;
  tab2_adrrege        temploy2.adrrege%type;
  tab2_adrregt        temploy2.adrregt%type;
  tab2_adrreg3        temploy2.adrreg3%type;
  tab2_adrreg4        temploy2.adrreg4%type;
  tab2_adrreg5        temploy2.adrreg5%type;
  tab2_coddistr       temploy2.coddistr%type;
  tab2_codprovr       temploy2.codprovr%type;
  tab2_codcntyr       temploy2.codcntyr%type;
  tab2_codpostr       temploy2.codpostr%type;
  tab2_adrconte       temploy2.adrconte%type;
  tab2_adrcontt       temploy2.adrcontt%type;
  tab2_adrcont3       temploy2.adrcont3%type;
  tab2_adrcont4       temploy2.adrcont4%type;
  tab2_adrcont5       temploy2.adrcont5%type;
  tab2_numprmid       temploy2.numprmid%type;
  tab2_dteprmst       temploy2.dteprmst%type;
  tab2_stamarry       temploy1.stamarry%type;
  tab2_email_emp      temploy1.email%type;
  tab2_nummobile      temploy1.nummobile%type;
  tab2_lineid         temploy1.lineid%type;
  tab2_numvisa        temploy2.numvisa%type;
  tab2_dtevisaexp     temploy2.dtevisaexp%type;
  tab2_codclnsc       temploy2.codclnsc%type;
  tab2_dteretire      temploy1.dteretire%type;
  tab2_adrreg         varchar2(4000 char);
  tab2_adrcont        varchar2(4000 char);
  tab2_codbank2       varchar2(4000 char);
  tab2_qtychedu       temploy3.qtychedu%type;
  tab2_qtychned       temploy3.qtychned%type;
  tab2_amttranb       temploy3.amttranb%type;
  tab2_dessubdistr    varchar2(4000 char);
  tab2_desdistr       varchar2(4000 char);
  tab2_desprovr       varchar2(4000 char);
  tab2_descntyr       varchar2(4000 char);
  tab2_dessubdistc    varchar2(4000 char);
  tab2_desdistc       varchar2(4000 char);
  tab2_desprovc       varchar2(4000 char);
  tab2_descntyc       varchar2(4000 char);
  tab2_desprovi       varchar2(4000 char);
--  tab2_namspous       varchar2(4000 char);
  tab2_desnote6       varchar2(4000 char);
  tab2_desc_codbank2  varchar2(4000 char);
  tab2_desc_codspocc  varchar2(4000 char);
  tab2_desc_codsppro  varchar2(4000 char);
  tab2_desc_codspcty  varchar2(4000 char);
-----*Spouse*
  tab2_codempidsp         tspouse.codempidsp%type;
  tab2_namimgsp           tspouse.namimgsp%type;
  tab2_codtitle           tspouse.codtitle%type;
  tab2_namfirst           tspouse.namfirste%type;
  tab2_namfirste          tspouse.namfirste%type;
  tab2_namfirstt          tspouse.namfirstt%type;
  tab2_namfirst3          tspouse.namfirst3%type;
  tab2_namfirst4          tspouse.namfirst4%type;
  tab2_namfirst5          tspouse.namfirst5%type;
  tab2_namlast            tspouse.namlaste%type;
  tab2_namlaste           tspouse.namlaste%type;
  tab2_namlastt           tspouse.namlastt%type;
  tab2_namlast3           tspouse.namlast3%type;
  tab2_namlast4           tspouse.namlast4%type;
  tab2_namlast5           tspouse.namlast5%type;
  tab2_namspe             tspouse.namspe%type;
  tab2_namspt             tspouse.namspt%type;
  tab2_namsp3             tspouse.namsp3%type;
  tab2_namsp4             tspouse.namsp4%type;
  tab2_namsp5             tspouse.namsp5%type;
  tab2_numoffid           tspouse.numoffid%type;
  tab2_numtaxid           tspouse.numtaxid%type;
  tab2_codspocc           tspouse.codspocc%type;
  tab2_dtespbd            tspouse.dtespbd%type;
  tab2_stalife            tspouse.stalife%type;
  tab2_staincom           tspouse.staincom%type;
  tab2_dtedthsp           tspouse.dtedthsp%type;
  tab2_desnoffi           tspouse.desnoffi%type;
  tab2_numfasp            tspouse.numfasp%type;
  tab2_nummosp            tspouse.nummosp%type;
  tab2_dtemarry           tspouse.dtemarry%type;
  tab2_codsppro           tspouse.codsppro%type;
  tab2_codspcty           tspouse.codspcty%type;
  tab2_desplreg           tspouse.desplreg%type;
  tab2_desnote            tspouse.desnote%type;
  tab2_filename           tspouse.filename%type;
  tab2_numrefdoc          tspouse.numrefdoc%type;
--------*End Spouse*
--------*Travel*
  tab2_typtrav            temploy1.typtrav%type;
  tab2_qtylength          temploy1.qtylength%type;
  tab2_carlicen           temploy1.carlicen%type;
  tab2_typfuel            temploy1.typfuel%type;
  tab2_codbusno           temploy1.codbusno%type;
  tab2_codbusrt           temploy1.codbusrt%type;
--------*End Travel*
--------*Family*
  tab2_codempfa         tfamily.codempfa%type;
  tab2_codtitlf         tfamily.codtitlf%type;
  tab2_namfstfe         tfamily.namfstfe%type;
  tab2_namfstft         tfamily.namfstft%type;
  tab2_namfstf3         tfamily.namfstf3%type;
  tab2_namfstf4         tfamily.namfstf4%type;
  tab2_namfstf5         tfamily.namfstf5%type;
  tab2_namlstfe         tfamily.namlstfe%type;
  tab2_namlstft         tfamily.namlstft%type;
  tab2_namlstf3         tfamily.namlstf3%type;
  tab2_namlstf4         tfamily.namlstf4%type;
  tab2_namlstf5         tfamily.namlstf5%type;
  tab2_namfathe         tfamily.namfathe%type;
  tab2_namfatht         tfamily.namfatht%type;
  tab2_namfath3         tfamily.namfath3%type;
  tab2_namfath4         tfamily.namfath4%type;
  tab2_namfath5         tfamily.namfath5%type;
  tab2_numofidf         tfamily.numofidf%type;
  tab2_dtebdfa          tfamily.dtebdfa%type;
  tab2_codfnatn         tfamily.codfnatn%type;
  tab2_codfrelg         tfamily.codfrelg%type;
  tab2_codfoccu         tfamily.codfoccu%type;
  tab2_staliff          tfamily.staliff%type;
  tab2_dtedeathf        tfamily.dtedeathf%type;
  tab2_filenamf         tfamily.filenamf%type;
  tab2_numrefdocf       tfamily.numrefdocf%type;
  tab2_codempmo         tfamily.codempmo%type;
  tab2_codtitlm         tfamily.codtitlm%type;
  tab2_namfstme         tfamily.namfstme%type;
  tab2_namfstmt         tfamily.namfstmt%type;
  tab2_namfstm3         tfamily.namfstm3%type;
  tab2_namfstm4         tfamily.namfstm4%type;
  tab2_namfstm5         tfamily.namfstm5%type;
  tab2_namlstme         tfamily.namlstme%type;
  tab2_namlstmt         tfamily.namlstmt%type;
  tab2_namlstm3         tfamily.namlstm3%type;
  tab2_namlstm4         tfamily.namlstm4%type;
  tab2_namlstm5         tfamily.namlstm5%type;
  tab2_nammothe         tfamily.nammothe%type;
  tab2_nammotht         tfamily.nammotht%type;
  tab2_nammoth3         tfamily.nammoth3%type;
  tab2_nammoth4         tfamily.nammoth4%type;
  tab2_nammoth5         tfamily.nammoth5%type;
  tab2_numofidm         tfamily.numofidm%type;
  tab2_dtebdmo          tfamily.dtebdmo%type;
  tab2_codmnatn         tfamily.codmnatn%type;
  tab2_codmrelg         tfamily.codmrelg%type;
  tab2_codmoccu         tfamily.codmoccu%type;
  tab2_stalifm          tfamily.stalifm%type;
  tab2_dtedeathm        tfamily.dtedeathm%type;
  tab2_filenamm         tfamily.filenamm%type;
  tab2_numrefdocm       tfamily.numrefdocm%type;
  tab2_codtitlc         tfamily.codtitlc%type;
  tab2_namfstce         tfamily.namfstce%type;
  tab2_namfstct         tfamily.namfstct%type;
  tab2_namfstc3         tfamily.namfstc3%type;
  tab2_namfstc4         tfamily.namfstc4%type;
  tab2_namfstc5         tfamily.namfstc5%type;
  tab2_namlstce         tfamily.namlstce%type;
  tab2_namlstct         tfamily.namlstct%type;
  tab2_namlstc3         tfamily.namlstc3%type;
  tab2_namlstc4         tfamily.namlstc4%type;
  tab2_namlstc5         tfamily.namlstc5%type;
  tab2_namconte         tfamily.namconte%type;
  tab2_namcontt         tfamily.namcontt%type;
  tab2_namcont3         tfamily.namcont3%type;
  tab2_namcont4         tfamily.namcont4%type;
  tab2_namcont5         tfamily.namcont5%type;
  tab2_adrcont1         tfamily.adrcont1%type;
  tab2_codpost          tfamily.codpost%type;
  tab2_numtele          tfamily.numtele%type;
  tab2_numfax           tfamily.numfax%type;
  tab2_email            tfamily.email%type;
  tab2_desrelat         tfamily.desrelat%type;
--------*End Family*
-----*Relative*
  tab2_relatives_numseq            trelatives.numseq%type;
  tab2_relatives_codemprl          trelatives.codemprl%type;
  tab2_relatives_namrele           trelatives.namrele%type;
  tab2_relatives_namrelt           trelatives.namrelt%type;
  tab2_relatives_namrel3           trelatives.namrel3%type;
  tab2_relatives_namrel4           trelatives.namrel4%type;
  tab2_relatives_namrel5           trelatives.namrel5%type;
  tab2_relatives_numtelec          trelatives.numtelec%type;
  tab2_relatives_adrcomt           trelatives.adrcomt%type;
-----*End Relative*
  tab4_status 	 	    varchar2(4000 char);
  --------*Childrn*
  tab4_numseq             tchildrn.numseq%type;
  tab4_codtitle           tchildrn.codtitle%type;
  tab4_namfirste          tchildrn.namfirste%type;
  tab4_namfirstt          tchildrn.namfirstt%type;
  tab4_namfirst3          tchildrn.namfirst3%type;
  tab4_namfirst4          tchildrn.namfirst4%type;
  tab4_namfirst5          tchildrn.namfirst5%type;
  tab4_namlaste           tchildrn.namlaste%type;
  tab4_namlastt           tchildrn.namlastt%type;
  tab4_namlast3           tchildrn.namlast3%type;
  tab4_namlast4           tchildrn.namlast4%type;
  tab4_namlast5           tchildrn.namlast5%type;
  tab4_namche             tchildrn.namche%type;
  tab4_namcht             tchildrn.namcht%type;
  tab4_namch3             tchildrn.namch3%type;
  tab4_namch4             tchildrn.namch4%type;
  tab4_namch5             tchildrn.namch5%type;
  tab4_numoffid           tchildrn.numoffid%type;
  tab4_dtechbd            tchildrn.dtechbd%type;
  tab4_codsex             tchildrn.codsex%type;
  tab4_codedlv            tchildrn.codedlv%type;
  tab4_stachld            tchildrn.stachld%type;
  tab4_stalife            tchildrn.stalife%type;
  tab4_dtedthch           tchildrn.dtedthch%type;
  tab4_flginc             tchildrn.flginc%type;
  tab4_flgedlv            tchildrn.flgedlv%type;
  tab4_flgdeduct          tchildrn.flgdeduct%type;
  tab4_stabf              tchildrn.stabf%type;
  tab4_filename           tchildrn.filename%type;
  tab4_numrefdoc          tchildrn.numrefdoc%type;
--------*End Childrn*
--
  tab6_routeno  		  varchar2(4000 char);
  tab6_codempap 		  varchar2(4000 char);
  tab6_codcompap		  varchar2(4000 char);
  tab6_codposap 		  varchar2(4000 char);
  tab6_staappr     	  varchar2(4000 char);
  tab6_approvno    	  varchar2(4000 char);
  tab6_codappr     	  varchar2(4000 char);
  tab6_dteappr     	  varchar2(4000 char);
  tab6_dtecancel     	varchar2(4000 char);
  tab6_remarkap    	  varchar2(4000 char);
  tab6_dteinput		    varchar2(4000 char);
  tab6_destrain	 	    varchar2(4000 char);
  tab6_dtetrain	 	    date;
  tab6_dtetren	 	    date;
  tab6_dtetr	 		    varchar2(4000 char);
  tab6_desplace	 	    varchar2(4000 char);
  tab6_desinstu	 	    varchar2(4000 char);
  tab6_status 	 	    varchar2(4000 char);
  tab6_desc_status    varchar2(4000 char);
  tab6_box_items      json_object_t;

  procedure get_index(json_str_input in clob, json_str_output out clob);
--  procedure get_detail2_tab1(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab1(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab5(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab6(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab8_table1(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab8_table2(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab8_table3(json_str_input in clob, json_str_output out clob);
  procedure get_detail2_tab9(json_str_input in clob, json_str_output out clob);
  procedure get_detail1(json_str_input in clob, json_str_output out clob);
  procedure get_education(json_str_input in clob, json_str_output out clob);
  procedure get_childen(json_str_input in clob, json_str_output out clob);
  procedure get_competency(json_str_input in clob, json_str_output out clob);
  procedure get_lang_abi(json_str_input in clob, json_str_output out clob);
  procedure get_his_reward(json_str_input in clob, json_str_output out clob);
  procedure get_work_exp(json_str_input in clob, json_str_output out clob);
  procedure get_ttrainbf(json_str_input in clob, json_str_output out clob);
  procedure process_approve(json_str_input in clob, json_str_output out clob);
--  procedure process_approve(json_str in clob, global_json_str in clob, p_result out clob);
  procedure get_others_data(json_str in clob, json_str_output out clob);

end; -- Package spec

/
